### ISSUE TITLE
no code

### ISSUE THREAD

**Issue by piedoom** [ColdSauce/stefan-botnet-cnc#1]
how am i going to make my bot net if there is no

**Comment by ColdSauce** [comment]
Use Śūnyatā

**Comment by ColdSauce** [comment]
Having code would require us to be attached to the botnet. Therefore, we write no code. This is zen. ![](http://images.huffingtonpost.com/2016-05-24-1464095578-8712366-201605201463749142206634112291245_10153298479604077_6629229701805783630_othumb-thumb.jpg)
